
import java.awt.CardLayout;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ProfieJack
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        setIconImage(new ImageIcon(
        getClass().getResource("assets/logo.png")
        ).getImage());
        setLocationRelativeTo(null);
        
        CardLayout cl = (CardLayout) cardLayoutParent.getLayout();
        cardLayoutParent.add(dashboardPanel, "Dashboard");
        cardLayoutParent.add(usersPanel, "Users");
        
        cl.show(cardLayoutParent, "Dashboard");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userModal.setLocationRelativeTo(this);
        userModal = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        fancyPanel3 = new fancyui.FancyPanel();
        jPanel1 = new javax.swing.JPanel();
        fancyPanel1 = new fancyui.FancyPanel();
        fancyImage1 = new fancyui.FancyImage();
        dashboardButton = new fancyui.FancyButton();
        fancyButton3 = new fancyui.FancyButton();
        fancyButton4 = new fancyui.FancyButton();
        usersButton = new fancyui.FancyButton();
        fancyButton6 = new fancyui.FancyButton();
        fancyButton7 = new fancyui.FancyButton();
        fancyButton5 = new fancyui.FancyButton();
        fancyPanel2 = new fancyui.FancyPanel();
        cardLayoutParent = new javax.swing.JPanel();
        usersPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fancyTextField2 = new fancyui.FancyTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        fancyTable3 = new fancyui.FancyTable();
        jPanel3 = new javax.swing.JPanel();
        addUserButton = new fancyui.FancyButton();
        fancyButton8 = new fancyui.FancyButton();
        fancyButton9 = new fancyui.FancyButton();
        dashboardPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fancyTable1 = new fancyui.FancyTable();
        jPanel2 = new javax.swing.JPanel();
        fancyPanel4 = new fancyui.FancyPanel();
        fancyPanel6 = new fancyui.FancyPanel();
        fancyPanel7 = new fancyui.FancyPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fancyTable2 = new fancyui.FancyTable();
        jLabel1 = new javax.swing.JLabel();
        fancyTextField1 = new fancyui.FancyTextField();

        userModal.setIconImage(new ImageIcon(
            getClass().getResource("assets/logo.png")
        ).getImage());
        userModal.setMinimumSize(new java.awt.Dimension(400, 400));
        userModal.setModal(false);
        userModal.setSize(new java.awt.Dimension(350, 450));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        fancyPanel3.setBorderColor(new java.awt.Color(217, 123, 79));
        fancyPanel3.setBorderEnabled(true);
        fancyPanel3.setCornerRadius(20);
        fancyPanel3.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel3.setSolidBackgroundEnabled(true);

        javax.swing.GroupLayout fancyPanel3Layout = new javax.swing.GroupLayout(fancyPanel3);
        fancyPanel3.setLayout(fancyPanel3Layout);
        fancyPanel3Layout.setHorizontalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        fancyPanel3Layout.setVerticalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout userModalLayout = new javax.swing.GroupLayout(userModal.getContentPane());
        userModal.getContentPane().setLayout(userModalLayout);
        userModalLayout.setHorizontalGroup(
            userModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        userModalLayout.setVerticalGroup(
            userModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Brewline Admin Dashboard");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        fancyPanel1.setBorderColor(new java.awt.Color(217, 123, 79));
        fancyPanel1.setBorderEnabled(true);
        fancyPanel1.setCornerRadius(20);
        fancyPanel1.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel1.setGradientStart(new java.awt.Color(232, 184, 127));

        fancyImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        dashboardButton.setText("Dashboard");
        dashboardButton.setHoverBackground(new java.awt.Color(74, 46, 36));
        dashboardButton.setHoverForeground(java.awt.Color.white);
        dashboardButton.addActionListener(this::dashboardButtonActionPerformed);

        fancyButton3.setText("Reports");
        fancyButton3.setHoverBackground(new java.awt.Color(74, 46, 36));
        fancyButton3.setHoverForeground(java.awt.Color.white);

        fancyButton4.setText("Sales");
        fancyButton4.setHoverBackground(new java.awt.Color(74, 46, 36));
        fancyButton4.setHoverForeground(java.awt.Color.white);

        usersButton.setText("Users");
        usersButton.setHoverBackground(new java.awt.Color(74, 46, 36));
        usersButton.setHoverForeground(java.awt.Color.white);
        usersButton.addActionListener(this::usersButtonActionPerformed);

        fancyButton6.setText("Settings");
        fancyButton6.setBorderColor(new java.awt.Color(232, 184, 127));
        fancyButton6.setHoverBackground(new java.awt.Color(74, 46, 36));
        fancyButton6.setHoverForeground(java.awt.Color.white);

        fancyButton7.setText("Logout");
        fancyButton7.setBorderColor(new java.awt.Color(232, 184, 127));
        fancyButton7.setHoverBackground(new java.awt.Color(74, 46, 36));
        fancyButton7.setHoverForeground(java.awt.Color.white);

        fancyButton5.setText("POS");
        fancyButton5.setHoverBackground(new java.awt.Color(74, 46, 36));
        fancyButton5.setHoverForeground(java.awt.Color.white);

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dashboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fancyButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fancyButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fancyButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fancyButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fancyButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        fancyPanel2.setBorderColor(new java.awt.Color(217, 123, 79));
        fancyPanel2.setBorderEnabled(true);
        fancyPanel2.setCornerRadius(20);
        fancyPanel2.setGradientStart(new java.awt.Color(232, 184, 127));
        fancyPanel2.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel2.setSolidBackgroundEnabled(true);

        cardLayoutParent.setBackground(new java.awt.Color(255, 255, 255));
        cardLayoutParent.setLayout(new java.awt.CardLayout());

        usersPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Qurova DEMO", 0, 24)); // NOI18N
        jLabel2.setText("User Management");

        fancyTextField2.setBorderColor(new java.awt.Color(217, 123, 79));
        fancyTextField2.setCornerRadius(4);
        fancyTextField2.setPlaceholder("Search");

        fancyTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        fancyTable3.setSelectionBackground(new java.awt.Color(232, 184, 127));
        fancyTable3.setGradientEnd(new java.awt.Color(232, 184, 127));
        fancyTable3.setGridLineColor(new java.awt.Color(232, 184, 127));
        fancyTable3.setHeaderBackground(new java.awt.Color(232, 184, 127));
        jScrollPane3.setViewportView(fancyTable3);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        addUserButton.setText("Add User");
        addUserButton.setBorderColor(new java.awt.Color(217, 123, 79));
        addUserButton.setHoverBackground(new java.awt.Color(74, 46, 36));
        addUserButton.setHoverForeground(java.awt.Color.white);
        addUserButton.addActionListener(this::addUserButtonActionPerformed);
        jPanel3.add(addUserButton);

        fancyButton8.setText("Update User");
        fancyButton8.setBorderColor(new java.awt.Color(217, 123, 79));
        fancyButton8.setHoverBackground(new java.awt.Color(74, 46, 36));
        fancyButton8.setHoverForeground(java.awt.Color.white);
        jPanel3.add(fancyButton8);

        fancyButton9.setText("Delete User");
        fancyButton9.setBorderColor(new java.awt.Color(217, 123, 79));
        fancyButton9.setHoverBackground(new java.awt.Color(74, 46, 36));
        fancyButton9.setHoverForeground(java.awt.Color.white);
        jPanel3.add(fancyButton9);

        javax.swing.GroupLayout usersPanelLayout = new javax.swing.GroupLayout(usersPanel);
        usersPanel.setLayout(usersPanelLayout);
        usersPanelLayout.setHorizontalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(usersPanelLayout.createSequentialGroup()
                        .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        usersPanelLayout.setVerticalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fancyTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardLayoutParent.add(usersPanel, "card2");

        dashboardPanel.setBackground(new java.awt.Color(255, 255, 255));

        fancyTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(fancyTable1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 1, 10, 0));

        fancyPanel4.setGradientAngle(-90);
        fancyPanel4.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel4.setGradientStart(new java.awt.Color(217, 123, 79));

        javax.swing.GroupLayout fancyPanel4Layout = new javax.swing.GroupLayout(fancyPanel4);
        fancyPanel4.setLayout(fancyPanel4Layout);
        fancyPanel4Layout.setHorizontalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        fancyPanel4Layout.setVerticalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(fancyPanel4);

        fancyPanel6.setGradientAngle(-90);
        fancyPanel6.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel6.setGradientStart(new java.awt.Color(217, 123, 79));

        javax.swing.GroupLayout fancyPanel6Layout = new javax.swing.GroupLayout(fancyPanel6);
        fancyPanel6.setLayout(fancyPanel6Layout);
        fancyPanel6Layout.setHorizontalGroup(
            fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        fancyPanel6Layout.setVerticalGroup(
            fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(fancyPanel6);

        fancyPanel7.setGradientAngle(-90);
        fancyPanel7.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel7.setGradientStart(new java.awt.Color(217, 123, 79));

        javax.swing.GroupLayout fancyPanel7Layout = new javax.swing.GroupLayout(fancyPanel7);
        fancyPanel7.setLayout(fancyPanel7Layout);
        fancyPanel7Layout.setHorizontalGroup(
            fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        fancyPanel7Layout.setVerticalGroup(
            fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(fancyPanel7);

        fancyTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(fancyTable2);

        jLabel1.setFont(new java.awt.Font("Qurova DEMO", 0, 24)); // NOI18N
        jLabel1.setText("Dashboard");

        fancyTextField1.setCornerRadius(4);
        fancyTextField1.setPlaceholder("Search");

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(fancyTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(fancyTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        cardLayoutParent.add(dashboardPanel, "card3");

        javax.swing.GroupLayout fancyPanel2Layout = new javax.swing.GroupLayout(fancyPanel2);
        fancyPanel2.setLayout(fancyPanel2Layout);
        fancyPanel2Layout.setHorizontalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cardLayoutParent, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        fancyPanel2Layout.setVerticalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cardLayoutParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(fancyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fancyPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
         CardLayout cl = (CardLayout) cardLayoutParent.getLayout();
         cl.show(cardLayoutParent, "Dashboard");
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void usersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersButtonActionPerformed
        CardLayout cl = (CardLayout) cardLayoutParent.getLayout();
         cl.show(cardLayoutParent, "Users");
    }//GEN-LAST:event_usersButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        userModal.show();
    }//GEN-LAST:event_addUserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyButton addUserButton;
    private javax.swing.JPanel cardLayoutParent;
    private fancyui.FancyButton dashboardButton;
    private javax.swing.JPanel dashboardPanel;
    private fancyui.FancyButton fancyButton3;
    private fancyui.FancyButton fancyButton4;
    private fancyui.FancyButton fancyButton5;
    private fancyui.FancyButton fancyButton6;
    private fancyui.FancyButton fancyButton7;
    private fancyui.FancyButton fancyButton8;
    private fancyui.FancyButton fancyButton9;
    private fancyui.FancyImage fancyImage1;
    private fancyui.FancyPanel fancyPanel1;
    private fancyui.FancyPanel fancyPanel2;
    private fancyui.FancyPanel fancyPanel3;
    private fancyui.FancyPanel fancyPanel4;
    private fancyui.FancyPanel fancyPanel6;
    private fancyui.FancyPanel fancyPanel7;
    private fancyui.FancyTable fancyTable1;
    private fancyui.FancyTable fancyTable2;
    private fancyui.FancyTable fancyTable3;
    private fancyui.FancyTextField fancyTextField1;
    private fancyui.FancyTextField fancyTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog userModal;
    private fancyui.FancyButton usersButton;
    private javax.swing.JPanel usersPanel;
    // End of variables declaration//GEN-END:variables
}
