
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ProfieJack
 */
public class POSDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(POSDashboard.class.getName());

    /**
     * Creates new form POSDashboard
     */
    public POSDashboard() {
        initComponents();
        setIconImage(new ImageIcon(
        getClass().getResource("assets/logo.png")
        ).getImage());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fancyPanel1 = new fancyui.FancyPanel();
        fancyImage1 = new fancyui.FancyImage();
        fancyButton2 = new fancyui.FancyButton();
        fancyButton3 = new fancyui.FancyButton();
        fancyPanel2 = new fancyui.FancyPanel();
        cardLayoutParent = new fancyui.FancyPanel();
        coffeePanel = new fancyui.FancyPanel();
        jPanel2 = new javax.swing.JPanel();
        fancyPanel5 = new fancyui.FancyPanel();
        fancyImage3 = new fancyui.FancyImage();
        jLabel2 = new javax.swing.JLabel();
        fancyPanel6 = new fancyui.FancyPanel();
        fancyImage4 = new fancyui.FancyImage();
        jLabel3 = new javax.swing.JLabel();
        fancyPanel7 = new fancyui.FancyPanel();
        fancyImage5 = new fancyui.FancyImage();
        jLabel4 = new javax.swing.JLabel();
        fancyPanel8 = new fancyui.FancyPanel();
        fancyImage6 = new fancyui.FancyImage();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        fancyPanel9 = new fancyui.FancyPanel();
        fancyImage7 = new fancyui.FancyImage();
        jLabel7 = new javax.swing.JLabel();
        fancyPanel10 = new fancyui.FancyPanel();
        fancyImage8 = new fancyui.FancyImage();
        jLabel8 = new javax.swing.JLabel();
        fancyPanel11 = new fancyui.FancyPanel();
        fancyImage9 = new fancyui.FancyImage();
        jLabel9 = new javax.swing.JLabel();
        fancyPanel12 = new fancyui.FancyPanel();
        fancyImage10 = new fancyui.FancyImage();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        fancyPanel13 = new fancyui.FancyPanel();
        fancyImage11 = new fancyui.FancyImage();
        jLabel12 = new javax.swing.JLabel();
        fancyPanel14 = new fancyui.FancyPanel();
        fancyImage12 = new fancyui.FancyImage();
        jLabel13 = new javax.swing.JLabel();
        fancyPanel15 = new fancyui.FancyPanel();
        fancyImage13 = new fancyui.FancyImage();
        jLabel14 = new javax.swing.JLabel();
        fancyPanel16 = new fancyui.FancyPanel();
        fancyImage14 = new fancyui.FancyImage();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fancyPanel3 = new fancyui.FancyPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        fancyPanel4 = new fancyui.FancyPanel();
        jLabel19 = new javax.swing.JLabel();
        fancyButton1 = new fancyui.FancyButton();
        fancyImage2 = new fancyui.FancyImage();
        fancyTextField1 = new fancyui.FancyTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Brewline POS");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        fancyPanel1.setBorderColor(new java.awt.Color(217, 123, 79));
        fancyPanel1.setBorderEnabled(true);
        fancyPanel1.setCornerRadius(20);
        fancyPanel1.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel1.setGradientStart(new java.awt.Color(232, 184, 127));

        fancyImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        fancyButton2.setText("POS");

        fancyButton3.setText("Products");

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fancyButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fancyButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fancyPanel2.setBorderColor(new java.awt.Color(217, 123, 79));
        fancyPanel2.setBorderEnabled(true);
        fancyPanel2.setCornerRadius(20);
        fancyPanel2.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel2.setSolidBackgroundEnabled(true);

        cardLayoutParent.setCornerRadius(10);
        cardLayoutParent.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        cardLayoutParent.setSolidBackgroundEnabled(true);
        cardLayoutParent.setLayout(new java.awt.CardLayout());

        coffeePanel.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        coffeePanel.setSolidBackgroundEnabled(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        fancyPanel5.setGradientAngle(-90);
        fancyPanel5.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel5.setGradientStart(new java.awt.Color(217, 123, 79));

        fancyImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/latte-art.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel2.setText("Latte");

        javax.swing.GroupLayout fancyPanel5Layout = new javax.swing.GroupLayout(fancyPanel5);
        fancyPanel5.setLayout(fancyPanel5Layout);
        fancyPanel5Layout.setHorizontalGroup(
            fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fancyPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        fancyPanel5Layout.setVerticalGroup(
            fancyPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(fancyImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel2.add(fancyPanel5);

        fancyPanel6.setGradientAngle(-90);
        fancyPanel6.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel6.setGradientStart(new java.awt.Color(217, 123, 79));

        fancyImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/latte-art.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Americano");

        javax.swing.GroupLayout fancyPanel6Layout = new javax.swing.GroupLayout(fancyPanel6);
        fancyPanel6.setLayout(fancyPanel6Layout);
        fancyPanel6Layout.setHorizontalGroup(
            fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel6Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(fancyImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(fancyPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel6Layout.setVerticalGroup(
            fancyPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(fancyImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.add(fancyPanel6);

        fancyPanel7.setGradientAngle(-90);
        fancyPanel7.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel7.setGradientStart(new java.awt.Color(217, 123, 79));

        fancyImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/latte-art.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cold Brew");

        javax.swing.GroupLayout fancyPanel7Layout = new javax.swing.GroupLayout(fancyPanel7);
        fancyPanel7.setLayout(fancyPanel7Layout);
        fancyPanel7Layout.setHorizontalGroup(
            fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel7Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(fancyImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(fancyPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel7Layout.setVerticalGroup(
            fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(fancyImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel2.add(fancyPanel7);

        fancyPanel8.setGradientAngle(-90);
        fancyPanel8.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel8.setGradientStart(new java.awt.Color(217, 123, 79));

        fancyImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/latte-art.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Frappe");

        javax.swing.GroupLayout fancyPanel8Layout = new javax.swing.GroupLayout(fancyPanel8);
        fancyPanel8.setLayout(fancyPanel8Layout);
        fancyPanel8Layout.setHorizontalGroup(
            fancyPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel8Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(fancyImage6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(fancyPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel8Layout.setVerticalGroup(
            fancyPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(fancyImage6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel2.add(fancyPanel8);

        jLabel6.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel6.setText("Coffee");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        fancyPanel9.setGradientAngle(-90);
        fancyPanel9.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel9.setGradientStart(new java.awt.Color(217, 123, 79));

        fancyImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/croissant.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Croissant");

        javax.swing.GroupLayout fancyPanel9Layout = new javax.swing.GroupLayout(fancyPanel9);
        fancyPanel9.setLayout(fancyPanel9Layout);
        fancyPanel9Layout.setHorizontalGroup(
            fancyPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel9Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(fancyImage7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(fancyPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel9Layout.setVerticalGroup(
            fancyPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(fancyImage7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel3.add(fancyPanel9);

        fancyPanel10.setGradientAngle(-90);
        fancyPanel10.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel10.setGradientStart(new java.awt.Color(217, 123, 79));

        fancyImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/croissant.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cookies");

        javax.swing.GroupLayout fancyPanel10Layout = new javax.swing.GroupLayout(fancyPanel10);
        fancyPanel10.setLayout(fancyPanel10Layout);
        fancyPanel10Layout.setHorizontalGroup(
            fancyPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel10Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(fancyImage8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(fancyPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel10Layout.setVerticalGroup(
            fancyPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(fancyImage8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel3.add(fancyPanel10);

        fancyPanel11.setGradientAngle(-90);
        fancyPanel11.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel11.setGradientStart(new java.awt.Color(217, 123, 79));

        fancyImage9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/croissant.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Brownies");

        javax.swing.GroupLayout fancyPanel11Layout = new javax.swing.GroupLayout(fancyPanel11);
        fancyPanel11.setLayout(fancyPanel11Layout);
        fancyPanel11Layout.setHorizontalGroup(
            fancyPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel11Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(fancyImage9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(fancyPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel11Layout.setVerticalGroup(
            fancyPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel11Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(fancyImage9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel3.add(fancyPanel11);

        fancyPanel12.setGradientAngle(-90);
        fancyPanel12.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel12.setGradientStart(new java.awt.Color(217, 123, 79));

        fancyImage10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/croissant.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pie");

        javax.swing.GroupLayout fancyPanel12Layout = new javax.swing.GroupLayout(fancyPanel12);
        fancyPanel12.setLayout(fancyPanel12Layout);
        fancyPanel12Layout.setHorizontalGroup(
            fancyPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel12Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(fancyImage10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(fancyPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel12Layout.setVerticalGroup(
            fancyPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel12Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(fancyImage10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel3.add(fancyPanel12);

        jLabel11.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel11.setText("Pastries");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        fancyPanel13.setGradientAngle(-90);
        fancyPanel13.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel13.setGradientStart(new java.awt.Color(217, 123, 79));

        fancyImage11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cake.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Blueberry");

        javax.swing.GroupLayout fancyPanel13Layout = new javax.swing.GroupLayout(fancyPanel13);
        fancyPanel13.setLayout(fancyPanel13Layout);
        fancyPanel13Layout.setHorizontalGroup(
            fancyPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel13Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(fancyImage11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(fancyPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel13Layout.setVerticalGroup(
            fancyPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel13Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(fancyImage11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel4.add(fancyPanel13);

        fancyPanel14.setGradientAngle(-90);
        fancyPanel14.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel14.setGradientStart(new java.awt.Color(217, 123, 79));

        fancyImage12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cake.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Choco moose");

        javax.swing.GroupLayout fancyPanel14Layout = new javax.swing.GroupLayout(fancyPanel14);
        fancyPanel14.setLayout(fancyPanel14Layout);
        fancyPanel14Layout.setHorizontalGroup(
            fancyPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel14Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(fancyImage12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(fancyPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel14Layout.setVerticalGroup(
            fancyPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel14Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(fancyImage12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel4.add(fancyPanel14);

        fancyPanel15.setGradientAngle(-90);
        fancyPanel15.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel15.setGradientStart(new java.awt.Color(217, 123, 79));

        fancyImage13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cake.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Strawberry");

        javax.swing.GroupLayout fancyPanel15Layout = new javax.swing.GroupLayout(fancyPanel15);
        fancyPanel15.setLayout(fancyPanel15Layout);
        fancyPanel15Layout.setHorizontalGroup(
            fancyPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel15Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(fancyImage13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(fancyPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel15Layout.setVerticalGroup(
            fancyPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel15Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(fancyImage13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel4.add(fancyPanel15);

        fancyPanel16.setGradientAngle(-90);
        fancyPanel16.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel16.setGradientStart(new java.awt.Color(217, 123, 79));

        fancyImage14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cake.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Ube Yam");

        javax.swing.GroupLayout fancyPanel16Layout = new javax.swing.GroupLayout(fancyPanel16);
        fancyPanel16.setLayout(fancyPanel16Layout);
        fancyPanel16Layout.setHorizontalGroup(
            fancyPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel16Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(fancyImage14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(fancyPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel16Layout.setVerticalGroup(
            fancyPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel16Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(fancyImage14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel4.add(fancyPanel16);

        jLabel16.setFont(new java.awt.Font("Qurova DEMO", 0, 18)); // NOI18N
        jLabel16.setText("Cakes");

        javax.swing.GroupLayout coffeePanelLayout = new javax.swing.GroupLayout(coffeePanel);
        coffeePanel.setLayout(coffeePanelLayout);
        coffeePanelLayout.setHorizontalGroup(
            coffeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coffeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coffeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(coffeePanelLayout.createSequentialGroup()
                        .addGroup(coffeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        coffeePanelLayout.setVerticalGroup(
            coffeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coffeePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cardLayoutParent.add(coffeePanel, "card2");

        javax.swing.GroupLayout fancyPanel2Layout = new javax.swing.GroupLayout(fancyPanel2);
        fancyPanel2.setLayout(fancyPanel2Layout);
        fancyPanel2Layout.setHorizontalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(cardLayoutParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel2Layout.setVerticalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardLayoutParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        fancyPanel3.setBorderColor(new java.awt.Color(217, 123, 79));
        fancyPanel3.setBorderEnabled(true);
        fancyPanel3.setCornerRadius(20);
        fancyPanel3.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel3.setSolidBackgroundEnabled(true);

        jLabel17.setText("Brewline");

        jLabel18.setText("Orders");

        jLabel20.setText("Cashier");

        jLabel21.setText("Administrator");

        javax.swing.GroupLayout fancyPanel3Layout = new javax.swing.GroupLayout(fancyPanel3);
        fancyPanel3.setLayout(fancyPanel3Layout);
        fancyPanel3Layout.setHorizontalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel3Layout.createSequentialGroup()
                        .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fancyPanel3Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel17))
                            .addGroup(fancyPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel18)))
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addGroup(fancyPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))))
                .addContainerGap())
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel3Layout.setVerticalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(64, 64, 64))
        );

        fancyPanel4.setBorderColor(new java.awt.Color(217, 123, 79));
        fancyPanel4.setBorderEnabled(true);
        fancyPanel4.setCornerRadius(20);
        fancyPanel4.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel4.setSolidBackgroundEnabled(true);

        jLabel19.setText("Total");

        javax.swing.GroupLayout fancyPanel4Layout = new javax.swing.GroupLayout(fancyPanel4);
        fancyPanel4.setLayout(fancyPanel4Layout);
        fancyPanel4Layout.setHorizontalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel4Layout.setVerticalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fancyButton1.setText("Checkout");
        fancyButton1.setBorderColor(new java.awt.Color(217, 123, 79));
        fancyButton1.setCornerRadius(12);

        fancyImage2.setCornerRadius(50);

        fancyTextField1.setBorderColor(new java.awt.Color(217, 123, 79));
        fancyTextField1.setCornerRadius(10);
        fancyTextField1.setPlaceholder("Search");

        jLabel1.setFont(new java.awt.Font("Qurova DEMO", 0, 36)); // NOI18N
        jLabel1.setText("Brewline");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(fancyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fancyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fancyPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fancyPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fancyButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fancyTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fancyImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(fancyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fancyImage2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fancyTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fancyPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fancyPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fancyPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fancyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new POSDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyPanel cardLayoutParent;
    private fancyui.FancyPanel coffeePanel;
    private fancyui.FancyButton fancyButton1;
    private fancyui.FancyButton fancyButton2;
    private fancyui.FancyButton fancyButton3;
    private fancyui.FancyImage fancyImage1;
    private fancyui.FancyImage fancyImage10;
    private fancyui.FancyImage fancyImage11;
    private fancyui.FancyImage fancyImage12;
    private fancyui.FancyImage fancyImage13;
    private fancyui.FancyImage fancyImage14;
    private fancyui.FancyImage fancyImage2;
    private fancyui.FancyImage fancyImage3;
    private fancyui.FancyImage fancyImage4;
    private fancyui.FancyImage fancyImage5;
    private fancyui.FancyImage fancyImage6;
    private fancyui.FancyImage fancyImage7;
    private fancyui.FancyImage fancyImage8;
    private fancyui.FancyImage fancyImage9;
    private fancyui.FancyPanel fancyPanel1;
    private fancyui.FancyPanel fancyPanel10;
    private fancyui.FancyPanel fancyPanel11;
    private fancyui.FancyPanel fancyPanel12;
    private fancyui.FancyPanel fancyPanel13;
    private fancyui.FancyPanel fancyPanel14;
    private fancyui.FancyPanel fancyPanel15;
    private fancyui.FancyPanel fancyPanel16;
    private fancyui.FancyPanel fancyPanel2;
    private fancyui.FancyPanel fancyPanel3;
    private fancyui.FancyPanel fancyPanel4;
    private fancyui.FancyPanel fancyPanel5;
    private fancyui.FancyPanel fancyPanel6;
    private fancyui.FancyPanel fancyPanel7;
    private fancyui.FancyPanel fancyPanel8;
    private fancyui.FancyPanel fancyPanel9;
    private fancyui.FancyTextField fancyTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
